default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: abtesting_development
  
test:
  <<: *default
  database: abtesting_test

production:
  <<: *default
  database: abtesting_production