# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9873e0b7ba5bca59e9a249591641898f900a17b5b1cb70d4704ab6ad041524ddbefa83c88e9fd2e8e9228905f946de06a40ef816c8ac01417e304b60eeb569b7

test:
  secret_key_base: d1ee8d9e9ff37464f3cfca8a8fa91b51b452f0d8be55963db85cbe15949243e624277508d2168fd4174522c64eb715784e7e4ed18904aa3979dd3b1e810449a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
